CREATE TABLE [dbo].[AdminAdUserPermissions] (
    [AdminAdUserId]                   UNIQUEIDENTIFIER NOT NULL,
    [Benutzerverwaltung]              NUMERIC(1)       NOT NULL,
    [BerichteBearbeiten]              NUMERIC(1)       NOT NULL,
    [BerichteLesen]                   NUMERIC(1)       NOT NULL,
    [BetriebBearbeiten]               NUMERIC(1)       NOT NULL,
    [BetriebLesen]                    NUMERIC(1)       NOT NULL,
    [DokumenteBearbeiten]             NUMERIC(1)       NOT NULL,
    [DokumenteLesen]                  NUMERIC(1)       NOT NULL,
    [GebietskoerperschaftBearbeiten]   NUMERIC(1)       NOT NULL,
    [GebietskoerperschaftLesen]        NUMERIC(1)       NOT NULL,
    [GrundDatenBearbeiten]            NUMERIC(1)       NOT NULL,
    [GrundDatenLesen]                 NUMERIC(1)       NOT NULL,
    [HilfetextBearbeiten]             NUMERIC(1)       NOT NULL,
    [HilfetextLesen]                  NUMERIC(1)       NOT NULL,
    [ImportExportSchemataBearbeiten]  NUMERIC(1)       NOT NULL,
    [ImportExportSchemataLesen]       NUMERIC(1)       NOT NULL,
    [LoginAlsBetrieb]                 NUMERIC(1)       NOT NULL,
    [LoginAlsGebietskoerperschaft]     NUMERIC(1)       NOT NULL,
    [LoginAlsSchule]                  NUMERIC(1)       NOT NULL,
    [LoginAlsSchulkind]               NUMERIC(1)       NOT NULL,
    [NachrichtenBearbeiten]           NUMERIC(1)       NOT NULL,
    [NachrichtenLesen]                NUMERIC(1)       NOT NULL,
    [NewsletterBearbeiten]            NUMERIC(1)       NOT NULL,
    [NewsletterLesen]                 NUMERIC(1)       NOT NULL,
    [SchuleBearbeiten]                NUMERIC(1)       NOT NULL,
    [SchuleLesen]                     NUMERIC(1)       NOT NULL,
    [SchulkindBearbeiten]             NUMERIC(1)       NOT NULL,
    [SchulkindLesen]                  NUMERIC(1)       NOT NULL,
    [SchulsystemBearbeiten]           NUMERIC(1)       NOT NULL,
    [SchulsystemLesen]                NUMERIC(1)       NOT NULL,
    [StatistikenBearbeiten]           NUMERIC(1)       NOT NULL,
    [StatistikenLesen]                NUMERIC(1)       NOT NULL,
    CONSTRAINT [PK_AdminAdUserPermissions_AdminAdUserId] PRIMARY KEY CLUSTERED ([AdminAdUserId] ASC),
    CONSTRAINT [FK_AdminAdUserPermissions_AdminAdUserId] FOREIGN KEY ([AdminAdUserId]) REFERENCES [dbo].[AdminAdUsers] ([Id]) ON DELETE CASCADE
);


