trigger: none

jobs:
- job: FinanzuebersichtBackendAdminCore
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: UseDotNet@2
    displayName: .NET 5.x SDK
    inputs:
      version: 5.x  
  - task: DotNetCoreCLI@2
    displayName: dotnet restore
    inputs:
      command: 'restore'
      feedsToUse: 'select'
      projects: 'Finanzuebersicht.Backends/Finanzuebersicht.Backend.Admin.Core/**/*.csproj'
  - task: DotNetCoreCLI@2
    displayName: dotnet build
    inputs:
      command: 'custom'
      projects: 'Finanzuebersicht.Backends/Finanzuebersicht.Backend.Admin.Core/**/*.csproj'
      custom: 'build'
      arguments: '-p:MSBuildTreatWarningsAsErrors=true --force'
  - task: DotNetCoreCLI@2
    displayName: dotnet test
    inputs:
      command: 'test'
      projects: 'Finanzuebersicht.Backends/Finanzuebersicht.Backend.Admin.Core/**/*.csproj'
      arguments: '-p:CollectCoverage=true -p:CoverletOutputFormat=cobertura -p:Exclude="[*Tests]*" -p:CoverletOutput=./coverage-result/'
  - task: reportgenerator@4
    displayName: Consolidate Code Coverage Results
    inputs:
      reports: '$(Build.SourcesDirectory)/**/coverage-result/coverage.cobertura.xml'
      targetdir: '$(Build.SourcesDirectory)/coverage-result'
  - task: PublishCodeCoverageResults@1
    displayName: 'Publish Code Coverage Results'
    inputs:
      codeCoverageTool: 'Cobertura'
      summaryFileLocation: '$(Build.SourcesDirectory)/coverage-result/Cobertura.xml'
      failIfCoverageEmpty: true
