# In this directory, run the following command to build this builder.
# $ gcloud builds submit

substitutions:
  _DOCKER_19: DOCKER_VERSION=5:19.03.9~3-0~ubuntu-focal
  _DOCKER_20: DOCKER_VERSION=5:20.10.14~3-0~ubuntu-focal

steps:
# Build all supported versions.
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--tag=gcr.io/$PROJECT_ID/docker:19.03.9'
  - '--file=Dockerfile'
  - '--build-arg=${_DOCKER_19}'
  - '.'
  id: '19.03.9'
  wait_for: ['base']
