- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--tag=gcr.io/firm-progress-279912/docker:19.03.9'
  - '--file=Dockerfile
  - '.'
  id: '19.03.9'
  wait_for: ['base']

  #args: [ 'build', '-t', 'us-central1-docker.pkg.dev/firm-progress-279912/finanzuebersicht:$SHORT_SHA', '.' ]
