# In this directory, run the following command to build this builder.
# $ gcloud builds submit

substitutions:
  _DOCKER_19: DOCKER_VERSION=5:19.03.9~3-0~ubuntu-focal
  _DOCKER_20: DOCKER_VERSION=5:20.10.14~3-0~ubuntu-focal

steps:
# Pre-requisite: build the base OS container; 'temp' is referenced in the
# Dockerfile for subsequent steps but is not pushed. Building this shared base
# image enables the versioned builders to share base layers.
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--tag=temp'
  - '--file=Dockerfile'
  - '.'
  id: 'base'

#
# Build all supported versions.
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--tag=gcr.io/$PROJECT_ID/docker:19.03.9'
  - '--file=Dockerfile'
  - '--build-arg=${_DOCKER_19}'
  - '.'
  id: '19.03.9'
  wait_for: ['base']
